### ISSUE TITLE
Implement `--non-billable` flag for `timetrace start`

### ISSUE THREAD

**Issue by dominikbraun** [dominikbraun/timetrace#168]
At the moment, billable records can be created using `timetrace start my-project --billable`. With PR #166, project records can be billable by default:

```yaml
# config.yml
projects:
  my-project:
    billable: true
```

Using this config, `timetrace start my-project` will produce a billable record.

But if `my-project` is configured to be billable by default, there also has to be a way to create non-billable records for that project. This should be possible by using a `--non-billable` flag.
