### ISSUE TITLE
Allow billable value to be set globally, by project, and by record

### ISSUE THREAD

**Issue by jenlampton** [dominikbraun/timetrace#248]
I've so far been unable to unable to create any record with a billable state set. Every project created is non-billable by default, and my config gile seems to have no affect on billing for new or existing projects. My file is named `config.yaml` but I also tried `config.yml` (since the README includes both).

**global default**
I would like to be able to set a default value for `billable` to true. This value will be used for every project that does not have billable specified. Perhaps somehting like
`timetrase set global billable yes`

**project default**
Additionally, I'd like to be able to specify a billable default state for each project on creation, something like 
`timetrace create project abc --billable=yes`

**record override**
And finally, I'd like to be able to specify a value for `billable` when a record is created, something like
`timetrace create record <PROJECT KEY> {<YYYY-MM-DD>|today|yesterday} <HH:MM> <HH:MM> --billable=yes`

Here's my current `config.yml`:
```yml
useDecimalHours: "On"
projects:
    blog:
        billable: true
    hqq:
        billable: true
    sfbra:
        billable: true
    vitals:
        billable: true
    datav:
        billable: true
```
And yes, the `useDecimalHours: "On"` does appear to be working as expected :) 

---

running timetrace version v0.14.3
